In [1]:
pip install fastf1

Defaulting to user installation because normal site-packages is not writeable
Collecting fastf1
  Using cached fastf1-3.8.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: cryptography in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (49.0.0)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (3.11.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (2.4.6)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (2.3.3)
Requirement already satisfied: platformdirs in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from fastf1) (4.5.0)
Requirement already satisfied: pydantic in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (2.13.4)
Requirement already satisfied: pyjwt in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (2.13.0)
Requirement already satisfied: python-dateutil in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from fastf1) (2.9.0.post0)
Requirement already satisfied: rapidfuzz in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (3.14.5)
Requirement already satisfied: requests-cache>=1.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (1.3.2)
Requirement already satisfied: requests>=2.30.0 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from fastf1) (2.32.5)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (1.17.1)
Requirement already satisfied: signalrcore in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (1.0.2)
Collecting timple>=0.1.6 (from fastf1)
  Using cached timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.3 in c:\users\user\appdata\roaming\python\python313\site-packages (from fastf1) (16.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (25.0)
Requirement already satisfied: pillow>=9 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2026.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from requests>=2.30.0->fastf1) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from requests>=2.30.0->fastf1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from requests>=2.30.0->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from requests>=2.30.0->fastf1) (2025.11.12)
Requirement already satisfied: attrs>=21.2 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from requests-cache>=1.0.0->fastf1) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from requests-cache>=1.0.0->fastf1) (26.1.0)
Requirement already satisfied: url-normalize>=2.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from requests-cache>=1.0.0->fastf1) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from cryptography->fastf1) (2.0.0)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\envs\alxenv\lib\site-packages (from cffi>=2.0.0->cryptography->fastf1) (2.23)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from pydantic->fastf1) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\user\appdata\roaming\python\python313\site-packages (from pydantic->fastf1) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pydantic->fastf1) (0.4.2)
Requirement already satisfied: msgpack==1.1.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from signalrcore->fastf1) (1.1.2)
Using cached fastf1-3.8.3-py3-none-any.whl (135 kB)
Using cached timple-0.1.8-py3-none-any.whl (17 kB)
Installing collected packages: timple, fastf1

   -------------------- ------------------- 1/2 [fastf1]
   -------------------- ------------------- 1/2 [fastf1]
   -------------------- ------------------- 1/2 [fastf1]
   ---------------------------------------- 2/2 [fastf1]

Successfully installed fastf1-3.8.3 timple-0.1.8
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd 
import fastf1
#CACHE_DIR = "../cache"
#fastf1.Cache.enable_cache('/app/cache') # Enable caching to speed up data retrieval

In [2]:
from matplotlib import pyplot as plt
import numpy as np

import fastf1
from fastf1 import plotting



# Enable Matplotlib patches for plotting timedelta values and load
# FastF1's dark color scheme
fastf1.plotting.setup_mpl(mpl_timedelta_support=True, color_scheme='fastf1')

In [4]:
print(engine.url)

mysql+pymysql://root:***@mysql:3306/f1_analytics

### Creation of the Race Results Fact Table. This pipeline retrieves and processes race results for a given year.

In [ ]:
def get_race_results(season, race, round_number):

    session = fastf1.get_session(season, race, 'R')
    session.load()

    results = session.results

    selected = results[[
        'DriverNumber',
        'Abbreviation',
        'TeamId',
        'ClassifiedPosition',
        'GridPosition',
        'Status',
        'Time',
        'Laps',
        'Points'
    ]]

    def format_time(row):
        time = row['Time']
        status = row['Status']

        if pd.isna(time):
            return "DNS" if status == 'Did not start' else "DNF"

        return f"{time.components.hours:02}:{time.components.minutes:02}:{time.components.seconds:02}.{int(time.components.milliseconds):03}"

    selected['Time'] = selected.apply(format_time, axis=1)

    selected['Points'] = selected['Points'].astype('Int64')
    selected['GridPosition'] = selected['GridPosition'].astype('Int64')

    # ⭐ FIXED LINE
    selected['Race'] = round_number

    selected['Season'] = season

    return selected


# Full season results. This function will loop through all races in the season and concatenate the results into a single DataFrame.
def get_season_results(season):

    schedule = fastf1.get_event_schedule(season, include_testing=False)

    races = schedule['EventName'].tolist()
    race_map = dict(zip(schedule['EventName'], schedule['RoundNumber']))

    all_results = []

    for race in races:
        try:
            df = get_race_results(season, race, race_map[race])
            all_results.append(df)
        except Exception as e:
            print(f"Skipping {race}: {e}")

    return pd.concat(all_results, ignore_index=True)

race_results_2026 = get_season_results(2026)

race_results_2026.to_sql("race_results", con=engine, if_exists="append", index=False)

### Creation of Circuits Dimension Table. This code block gets all event data for the 2026 season, extracts the relevant columns and loads the data into MySQL Database

In [6]:
def get_event_schedule(season):
    schedule = fastf1.get_event_schedule(season, include_testing=False)
    selected_schedule = schedule[[
        'RoundNumber',
        'EventName',
        'Country',
        'EventDate',
]]
    return selected_schedule

get_event_schedule(2026)

circuits = get_event_schedule(2026)
circuits.to_sql('Circuits', con=engine, if_exists='replace', index=False)

22

### Creation of Drivers Dimension Table. This code block gets all drivers for the 2026 season, extracts the relevant columns and loads the data into MySQL Database

In [ ]:
def get_driver_list(season):
    session = fastf1.get_session(2026, 'Australia', 'R')
    session.load()
    selected_drivers = session.results[[
        'DriverNumber',
        'Abbreviation',
        'FullName',
        'TeamName',
]]
    selected_drivers = selected_drivers.rename(columns={
        'FullName': 'DriverName'
    })
    return selected_drivers

get_driver_list(2026)


drivers = get_driver_list(2026)
drivers.to_sql('drivers', con=engine, if_exists='replace', index=False)

### Creation of Constructors Dimension Table. This code block gets all teams for the 2026 season, extracts the relevant columns and loads the data into MySQL Database

In [ ]:
def get_constructor_list(season):
    session = fastf1.get_session(2026, 'Australia', 'R')
    session.load()
    selected_constructors = session.results[[
        'TeamId',
        'TeamName'
]].drop_duplicates().reset_index(drop=True)
    
    return selected_constructors

get_constructor_list(2026)

constructors = get_constructor_list(2026)
constructors.to_sql('constructors', con=engine, if_exists='replace', index=False)

In [17]:
session = fastf1.get_session(2026, 'Australia', 'R')
session.load()
session.laps

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:03:56.437000,NOR,1,0 days 00:01:36.458000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:18.163000,...,True,McLaren,0 days 01:02:19.743000,2026-03-08 04:03:26.366,1,6.0,False,,False,False
1,0 days 01:05:23.781000,NOR,1,0 days 00:01:27.344000,2.0,1.0,NaT,NaT,0 days 00:00:31.074000,0 days 00:00:18.116000,...,True,McLaren,0 days 01:03:56.437000,2026-03-08 04:05:03.060,1,6.0,False,,False,True
2,0 days 01:06:50.644000,NOR,1,0 days 00:01:26.863000,3.0,1.0,NaT,NaT,0 days 00:00:30.541000,0 days 00:00:18.252000,...,True,McLaren,0 days 01:05:23.781000,2026-03-08 04:06:30.404,1,7.0,False,,False,True
3,0 days 01:08:16.501000,NOR,1,0 days 00:01:25.857000,4.0,1.0,NaT,NaT,0 days 00:00:30.190000,0 days 00:00:18.193000,...,True,McLaren,0 days 01:06:50.644000,2026-03-08 04:07:57.267,1,7.0,False,,False,True
4,0 days 01:09:42.074000,NOR,1,0 days 00:01:25.573000,5.0,1.0,NaT,NaT,0 days 00:00:29.930000,0 days 00:00:17.868000,...,True,McLaren,0 days 01:08:16.501000,2026-03-08 04:09:23.124,1,7.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,0 days 02:19:49.241000,BEA,87,0 days 00:01:24.615000,53.0,2.0,NaT,NaT,0 days 00:00:29.699000,0 days 00:00:17.937000,...,True,Haas F1 Team,0 days 02:18:24.626000,2026-03-08 05:19:31.249,1,7.0,False,,False,True
1002,0 days 02:21:13.851000,BEA,87,0 days 00:01:24.610000,54.0,2.0,NaT,NaT,0 days 00:00:29.965000,0 days 00:00:17.876000,...,True,Haas F1 Team,0 days 02:19:49.241000,2026-03-08 05:20:55.864,1,7.0,False,,False,True
1003,0 days 02:22:38.351000,BEA,87,0 days 00:01:24.500000,55.0,2.0,NaT,NaT,0 days 00:00:29.725000,0 days 00:00:17.930000,...,True,Haas F1 Team,0 days 02:21:13.851000,2026-03-08 05:22:20.474,1,7.0,False,,False,True
1004,0 days 02:24:04.790000,BEA,87,0 days 00:01:26.439000,56.0,2.0,NaT,NaT,0 days 00:00:29.768000,0 days 00:00:17.858000,...,True,Haas F1 Team,0 days 02:22:38.351000,2026-03-08 05:23:44.974,1,7.0,False,,False,True
1005,0 days 02:25:31.439000,BEA,87,0 days 00:01:26.649000,57.0,2.0,NaT,NaT,0 days 00:00:30.005000,0 days 00:00:17.905000,...,True,Haas F1 Team,0 days 02:24:04.790000,2026-03-08 05:25:11.413,1,7.0,False,,False,True

### Creation of Lap Times Fact Table. This pipeline gets lap times for all drivers, extracts the relevant columns and loads the data into MySQL Database

In [ ]:
def get_lap_times(season, race, round_number):

    try:
        session = fastf1.get_session(season, race, 'R')
        session.load()

        laps = session.laps.copy()

        selected = laps[[
            'DriverNumber',
            'LapNumber',
            'Sector1Time',
            'Sector2Time',
            'Sector3Time',
            'LapTime',
            'Compound',
            'TyreLife',
            'Stint',
            'IsPersonalBest',
            'Position'
        ]].copy()

        # convert lap time to seconds
        selected['LapTime'] = selected['LapTime'].dt.total_seconds()
        selected['Sector1Time'] = selected['Sector1Time'].dt.total_seconds()
        selected['Sector2Time'] = selected['Sector2Time'].dt.total_seconds()
        selected['Sector3Time'] = selected['Sector3Time'].dt.total_seconds()

        # add identifiers
        selected['Season'] = season
        selected['RaceID'] = round_number

        # skip empty / future races
        if selected['LapTime'].isna().all():
            print(f"Skipping {race} (no lap data yet)")
            return None

        return selected

    except Exception as e:
        print(f"Skipping {race}: {e}")
        return None

#season data for all races in the season. This will loop through all races and concatenate the lap data into a single DataFrame.
def get_season_laps(season):

    schedule = fastf1.get_event_schedule(season, include_testing=False)
    races = schedule['EventName'].tolist()

    all_laps = []

    for race in races:
        df = get_lap_times(season, race, schedule[schedule['EventName'] == race]['RoundNumber'].iloc[0])

        if df is not None:
            all_laps.append(df)

    return pd.concat(all_laps, ignore_index=True)

#get lap data for the entire season. This will take a while to run as it has to loop through all races and all laps, but it will fill in as the season progresses.
lap_times_2026 = get_season_laps(2026)

lap_times_2026.to_sql(
    "lap_times",
    con=engine,
    if_exists="append",
    index=False
)

In [5]:
session = fastf1.get_session(2026, 'Barcelona Grand Prix', 'R')
session.load()
session.laps

core           INFO 	Loading data for Barcelona Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['44', '63', '1', '3', '81', '6', '10', '30', '41', '43', '5', '55', '31', '11', '16', '12', '87', '23', '14', '27', '77', '18']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:55:08.537000,NOR,1,0 days 00:01:27.198000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:33.656000,...,True,McLaren,0 days 00:53:41.090000,2026-06-14 13:03:27.855,1,4.0,False,,False,False
1,0 days 00:56:30.788000,NOR,1,0 days 00:01:22.251000,2.0,1.0,NaT,NaT,0 days 00:00:23.744000,0 days 00:00:33.611000,...,True,McLaren,0 days 00:55:08.537000,2026-06-14 13:04:55.302,1,4.0,False,,False,True
2,0 days 00:57:53.210000,NOR,1,0 days 00:01:22.422000,3.0,1.0,NaT,NaT,0 days 00:00:23.976000,0 days 00:00:33.500000,...,True,McLaren,0 days 00:56:30.788000,2026-06-14 13:06:17.553,1,4.0,False,,False,True
3,0 days 00:59:15.983000,NOR,1,0 days 00:01:22.773000,4.0,1.0,NaT,NaT,0 days 00:00:23.999000,0 days 00:00:33.552000,...,True,McLaren,0 days 00:57:53.210000,2026-06-14 13:07:39.975,1,4.0,False,,False,True
4,0 days 01:00:39.270000,NOR,1,0 days 00:01:23.287000,5.0,1.0,NaT,NaT,0 days 00:00:24.189000,0 days 00:00:33.813000,...,True,McLaren,0 days 00:59:15.983000,2026-06-14 13:09:02.748,1,4.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1231,0 days 02:14:22.044000,BEA,87,0 days 00:01:27.738000,56.0,3.0,NaT,NaT,0 days 00:00:26.538000,0 days 00:00:35.203000,...,False,Haas F1 Team,0 days 02:12:54.306000,2026-06-14 14:22:41.071,1,13.0,False,,False,True
1232,0 days 02:15:46.781000,BEA,87,0 days 00:01:24.737000,57.0,3.0,NaT,NaT,0 days 00:00:24.606000,0 days 00:00:34.204000,...,False,Haas F1 Team,0 days 02:14:22.044000,2026-06-14 14:24:08.809,1,13.0,False,,False,True
1233,0 days 02:17:11.160000,BEA,87,0 days 00:01:24.379000,58.0,3.0,NaT,NaT,0 days 00:00:24.556000,0 days 00:00:34.091000,...,False,Haas F1 Team,0 days 02:15:46.781000,2026-06-14 14:25:33.546,1,13.0,False,,False,True
1234,0 days 02:18:35.266000,BEA,87,0 days 00:01:24.106000,59.0,3.0,NaT,NaT,0 days 00:00:24.540000,0 days 00:00:33.913000,...,False,Haas F1 Team,0 days 02:17:11.160000,2026-06-14 14:26:57.925,1,13.0,False,,False,True
1235,0 days 02:20:18.787000,BEA,87,0 days 00:01:43.521000,60.0,3.0,NaT,0 days 02:20:15.746000,0 days 00:00:24.547000,0 days 00:00:34.049000,...,False,Haas F1 Team,0 days 02:18:35.266000,2026-06-14 14:28:22.031,126,15.0,False,,False,False